  
exports.user = {
    "id":null,    
    "uid":null,
    "fullName":null,
    "username":null,
    "usernameLower":null,
    "phoneNumber":null,    
    "email":null,
    "password":null,
    "profilePicture":null,
    "likedItems":null,
    "favoriteItems":null,
    "items":null,
    "likes":null,
    "rating":null,
    "rateTable":null,
    "swaps":null,
    "swapsCompleted":null,
    "reports":null,
    "lastSeen":null,
    "dateCreated":null,
    "status":null,
    "token":null,
    "deviceDetail":null
} 